// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: steam.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamService_AuthUserTicket_FullMethodName = "/user.SteamService/AuthUserTicket"
	SteamService_Ping_FullMethodName           = "/user.SteamService/Ping"
)

// SteamServiceClient is the client API for SteamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SteamServiceClient interface {
	AuthUserTicket(ctx context.Context, in *UserTicket, opts ...grpc.CallOption) (*AuthUserTicketResponse, error)
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
}

type steamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamServiceClient(cc grpc.ClientConnInterface) SteamServiceClient {
	return &steamServiceClient{cc}
}

func (c *steamServiceClient) AuthUserTicket(ctx context.Context, in *UserTicket, opts ...grpc.CallOption) (*AuthUserTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUserTicketResponse)
	err := c.cc.Invoke(ctx, SteamService_AuthUserTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steamServiceClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, SteamService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamServiceServer is the server API for SteamService service.
// All implementations must embed UnimplementedSteamServiceServer
// for forward compatibility.
type SteamServiceServer interface {
	AuthUserTicket(context.Context, *UserTicket) (*AuthUserTicketResponse, error)
	Ping(context.Context, *PingMessage) (*PingMessage, error)
	mustEmbedUnimplementedSteamServiceServer()
}

// UnimplementedSteamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamServiceServer struct{}

func (UnimplementedSteamServiceServer) AuthUserTicket(context.Context, *UserTicket) (*AuthUserTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUserTicket not implemented")
}
func (UnimplementedSteamServiceServer) Ping(context.Context, *PingMessage) (*PingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSteamServiceServer) mustEmbedUnimplementedSteamServiceServer() {}
func (UnimplementedSteamServiceServer) testEmbeddedByValue()                      {}

// UnsafeSteamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamServiceServer will
// result in compilation errors.
type UnsafeSteamServiceServer interface {
	mustEmbedUnimplementedSteamServiceServer()
}

func RegisterSteamServiceServer(s grpc.ServiceRegistrar, srv SteamServiceServer) {
	// If the following call pancis, it indicates UnimplementedSteamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamService_ServiceDesc, srv)
}

func _SteamService_AuthUserTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTicket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamServiceServer).AuthUserTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamService_AuthUserTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamServiceServer).AuthUserTicket(ctx, req.(*UserTicket))
	}
	return interceptor(ctx, in, info, handler)
}

func _SteamService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamServiceServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamService_ServiceDesc is the grpc.ServiceDesc for SteamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.SteamService",
	HandlerType: (*SteamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthUserTicket",
			Handler:    _SteamService_AuthUserTicket_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SteamService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steam.proto",
}
